modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "elderlyguardians"
version = "${version}"
displayName = "ElderlyGuardians"
authors = "MuriPlz"
description = '''
Economy for CubedWorlds network
'''
#logoFile = ""

[[dependencies.elderlyguardians]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.elderlyguardians]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "elderlyguardians.mixins.json"
